### PR TITLE
Remove moot `version` property from bower.json

### PR DESCRIPTION
**Pull request by kkirsche**
Per bower/bower.json-spec@a325da3

### CODE REVIEW

**Comment by lannymcnie** [comment]
What benefit is there to removing the version info?

**Comment by kkirsche** [comment]
It isn't and hasn't been used. Removing removes a pointless value which isn't used to reduce the need to deal with one more version bump each time you do a release when it isn't even used.

**Comment by lannymcnie** [comment]
https://twitter.com/bower/status/609374594949120000
Will consider removing from all CreateJS libs.

**Comment by kkirsche** [comment]
Didn't believe me huh?

**Comment by lannymcnie** [comment]
The main thing is that the version provides some additional info about the current build, whether or not bower actually uses it. It may not be necessary, but it doesn't hurt anything being there. Our build process automatically updates the bower version, so maintenance is a non-issue.

**Pull request closed without merging**
